name: Deploy Next.js Frontend to Server

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.FRONTEND_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.FRONTEND_SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server via rsync
        run: |
          # Deploy all necessary files including ecosystem.config.js
          rsync -avz --delete \
            --exclude='.git/' \
            --exclude='node_modules/' \
            --exclude='.env.local' \
            --exclude='.env*.local' \
            ./ ${{ secrets.FRONTEND_SERVER_USER }}@${{ secrets.FRONTEND_SERVER_HOST }}:/home/propenchill/gro-fe/

      - name: Install dependencies and restart service on server
        run: |
          ssh ${{ secrets.FRONTEND_SERVER_USER }}@${{ secrets.FRONTEND_SERVER_HOST }} '
            cd /home/propenchill/gro-fe
            
            # Install all dependencies (including TypeScript)
            npm install
            
            # Build the project on server
            npm run build
            
            # Check if PM2 is installed, install if not (without sudo in CI)
            if ! command -v pm2 &> /dev/null; then
              echo "PM2 not found, please install manually on server"
              exit 1
            fi
            
            # Start or reload the application
            if pm2 describe gro-frontend > /dev/null 2>&1; then
              pm2 reload gro-frontend --update-env
            else
              pm2 start ecosystem.config.js
            fi
            
            # Save PM2 configuration
            pm2 save
          '