name: Deploy Next.js Frontend to Server

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.FRONTEND_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.FRONTEND_SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server via rsync
        run: |
          # Deploy all necessary files
          rsync -avz --delete \
            --exclude='.git/' \
            --exclude='node_modules/' \
            --exclude='.env.local' \
            --exclude='.env*.local' \
            ./ ${{ secrets.FRONTEND_SERVER_USER }}@${{ secrets.FRONTEND_SERVER_HOST }}:/home/propenchill/gro-fe/

      - name: Install dependencies and restart service on server
        run: |
          ssh ${{ secrets.FRONTEND_SERVER_USER }}@${{ secrets.FRONTEND_SERVER_HOST }} '
            cd /home/propenchill/gro-fe
            npm install --omit=dev
            sudo npm install -g pm2 || echo "PM2 already installed"
            npm run build
            pm2 reload ecosystem.config.js --update-env || pm2 start ecosystem.config.js
          '